server.port=8000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/connection
spring.datasource.username=sudarshanmhasrup
spring.datasource.password=Lockednow